// AUTO-GENERATED by qec_pipeline/qec_advantage.py. Do not edit by hand.
// Quantum vs classical for QUANTUM ERROR CORRECTION (surface-code memory).

export interface AdvantageQECRecord {
  d: number; physical_qubits: number; rounds: number;
  logical_error_per_round: number; lambda_suppression: number;
  classical_exact_time_s: number; classical_stim_time_s: number; qpu_projected_time_s: number;
}
export interface HardwareRun {
  backend: string; code: string; distance: number; rounds: number; shots: number;
  wallclock_s: number; logical_error_per_round: number; physical_error_per_round: number; job_id: string;
}

export const ADVANTAGE_RECORDS: AdvantageQECRecord[] = [
  { d: 3, physical_qubits: 17, rounds: 3, logical_error_per_round: 0.005945415725, lambda_suppression: 1.0, classical_exact_time_s: 0.000131072, classical_stim_time_s: 0.020139, qpu_projected_time_s: 3e-06 },
  { d: 5, physical_qubits: 49, rounds: 5, logical_error_per_round: 0.002601939806, lambda_suppression: 2.285, classical_exact_time_s: 562949.953421312, classical_stim_time_s: 0.109675, qpu_projected_time_s: 5e-06 },
  { d: 7, physical_qubits: 97, rounds: 7, logical_error_per_round: 0.001205107355, lambda_suppression: 2.159, classical_exact_time_s: 1.584563250285287e+20, classical_stim_time_s: 0.353954, qpu_projected_time_s: 7e-06 },
  { d: 9, physical_qubits: 161, rounds: 9, logical_error_per_round: 0.000555237709, lambda_suppression: 2.17, classical_exact_time_s: 2.923003274661806e+39, classical_stim_time_s: 0.805069, qpu_projected_time_s: 9e-06 }
];

export const ADVANTAGE_HARDWARE: HardwareRun | null = null;

export const ADVANTAGE_GAIN = {"atDistance": 9, "atQubits": 161, "classicalTimeS": 2.923003274661806e+39, "qpuTimeS": 9e-06, "speedup": 3.2477814162908955e+44, "finalLogicalError": 0.000555237709238543, "meanLambda": 1.9};

export const ADVANTAGE_META = {
  task: "Surface-code memory",
  material: "Ta/sapphire",
  shots: 40000,
  cycleTimeUs: 1.0,
  generatedAt: "2026-05-30T22:48:53Z",
};
