// AUTO-GENERATED by qec_pipeline/export_catalogs.py from cryostat_catalog.py.
// Do not edit by hand. Tier-1 commercial dilution refrigerators.

export interface Cryostat {
  id: string; name: string; manufacturer: string;
  baseTempMK: number; operatingTempMK: number; coolingPowerUw20mK: number;
  maxCoaxLines: number; maxQubits: number;
  cosmicRayShielding: string; vibrationIsolation: string; magneticShielding: string;
  maturityTier: number; notes: string;
}

export const CRYOSTATS: Cryostat[] = [
  { id: 'oxford_proteox_mx', name: 'Oxford Proteox MX', manufacturer: 'Oxford Instruments NanoScience', baseTempMK: 7, operatingTempMK: 10, coolingPowerUw20mK: 20, maxCoaxLines: 80, maxQubits: 160, cosmicRayShielding: 'none', vibrationIsolation: 'passive', magneticShielding: 'enhanced', maturityTier: 1, notes: 'Good balance of size, cooling power, and accessibility.' },
  { id: 'oxford_proteox_lx', name: 'Oxford Proteox LX', manufacturer: 'Oxford Instruments NanoScience', baseTempMK: 7, operatingTempMK: 10, coolingPowerUw20mK: 40, maxCoaxLines: 200, maxQubits: 400, cosmicRayShielding: 'none', vibrationIsolation: 'active', magneticShielding: 'enhanced', maturityTier: 1, notes: '' },
  { id: 'oxford_triton_200', name: 'Oxford Triton 200', manufacturer: 'Oxford Instruments NanoScience', baseTempMK: 10, operatingTempMK: 15, coolingPowerUw20mK: 15, maxCoaxLines: 64, maxQubits: 120, cosmicRayShielding: 'none', vibrationIsolation: 'passive', magneticShielding: 'standard', maturityTier: 1, notes: 'The bread-and-butter fridge for the field. Aging but reliable.' },
  { id: 'oxford_triton_500', name: 'Oxford Triton 500', manufacturer: 'Oxford Instruments NanoScience', baseTempMK: 8, operatingTempMK: 12, coolingPowerUw20mK: 30, maxCoaxLines: 120, maxQubits: 240, cosmicRayShielding: 'none', vibrationIsolation: 'passive', magneticShielding: 'standard', maturityTier: 1, notes: '' },
  { id: 'bluefors_ld', name: 'Bluefors LD', manufacturer: 'Bluefors', baseTempMK: 10, operatingTempMK: 15, coolingPowerUw20mK: 10, maxCoaxLines: 48, maxQubits: 80, cosmicRayShielding: 'none', vibrationIsolation: 'passive', magneticShielding: 'standard', maturityTier: 1, notes: '' },
  { id: 'bluefors_xld', name: 'Bluefors XLD', manufacturer: 'Bluefors', baseTempMK: 7, operatingTempMK: 10, coolingPowerUw20mK: 30, maxCoaxLines: 144, maxQubits: 280, cosmicRayShielding: 'none', vibrationIsolation: 'active', magneticShielding: 'enhanced', maturityTier: 1, notes: "Industry standard. If you've seen a quantum computer in a video, this is probably the fridge." },
  { id: 'bluefors_kide', name: 'Bluefors KIDE', manufacturer: 'Bluefors', baseTempMK: 7, operatingTempMK: 10, coolingPowerUw20mK: 50, maxCoaxLines: 500, maxQubits: 1000, cosmicRayShielding: 'none', vibrationIsolation: 'decoupled_frame', magneticShielding: 'mu-metal+SC', maturityTier: 1, notes: 'The platform IBM Quantum System Two is built on. Engineered for >1000 qubit scale.' },
  { id: 'leiden_cf_cs81', name: 'Leiden CF-CS81 (Dry Dilution)', manufacturer: 'Leiden Cryogenics', baseTempMK: 8, operatingTempMK: 12, coolingPowerUw20mK: 25, maxCoaxLines: 72, maxQubits: 140, cosmicRayShielding: 'none', vibrationIsolation: 'passive', magneticShielding: 'standard', maturityTier: 1, notes: '' }
];

export const CRYOSTATS_META = {
  source: "cryostat_catalog.py",
  total: 8,
  generatedAt: "2026-05-31T01:25:42Z",
};
