// AUTO-GENERATED by qec_pipeline/materials_search_benchmark.py. Do not edit by hand.
// Measured combinatorial materials search: classical CPU vs XpyQ vs IBM Quantum.

export interface HardwareSample {
  stack_id: string; backend: string; shots: number; wallclock_s: number;
  execution_s?: number; job_id: string; hardware: boolean; oracle_qubits: number;
}

export interface MaterialsSearchBenchmark {
  combos: number;
  groverIters: number;
  classical: {
    totalWallS: number; perEvalS: number; stackOracleS: number; searchS: number;
    cpuCores: number; gpuProjectedS: number;
    stacksRun: number; source: string;
  };
  xpyq: {
    totalWallS: number; perEvalS: number; groverS: number; groverIters: number;
    stacksRun: number; source: string; baseUrl: string | null;
  };
  ibm: {
    perOracleS: number; groverS: number; groverIters: number;
    samplesRun: number; source: string; samples: HardwareSample[];
  };
  sweep: { n: number; classical: number; gpu: number; xpyq: number; ibm: number }[];
  barComparison: { label: string; timeS: number; source: string }[];
  meta: { generatedAt: string; scaleReference: number };
}

export const MATERIALS_SEARCH_BENCHMARK: MaterialsSearchBenchmark = {
  combos: 120,
  groverIters: 9,
  classical: {"totalWallS": 0.000979, "perEvalS": 8e-06, "stackOracleS": 0.279759, "searchS": 33.5711, "cpuCores": 8, "gpuProjectedS": 0.016392, "stacksRun": 120, "source": "measured_cpu"},
  xpyq: {"totalWallS": 33.5711, "perEvalS": 0.279759, "groverS": 2.517833, "groverIters": 9, "stacksRun": 120, "source": "xpyq_api", "baseUrl": "https://xpyq-lib-production.up.railway.app", "uiBase": "https://xpyq.vercel.app/functions"},
  ibm: {
    perOracleS: 2.361388,
    groverS: 21.252496,
    groverIters: 9,
    samplesRun: 5,
    source: "ibm_hardware",
    samples: [
  {"stack_id": "tin-metal|mgo|aluminium|granular-al", "backend": "ibm_marrakesh", "shots": 4096, "wallclock_s": 7.224, "job_id": "d8e3udbalsvc738voeu0", "hardware": true, "oracle_qubits": 4, "execution_s": 1.969295},
  {"stack_id": "tantalum|sapphire|alox|nbtin", "backend": "ibm_marrakesh", "shots": 4096, "wallclock_s": 8.787, "job_id": "d8e3ug87jphs739k6jpg", "hardware": true, "oracle_qubits": 4, "execution_s": 3.95526},
  {"stack_id": "tantalum|sapphire|aluminium|tin", "backend": "ibm_marrakesh", "shots": 4096, "wallclock_s": 6.784, "job_id": "d8e3uk1vjngc73anrp90", "hardware": true, "oracle_qubits": 4, "execution_s": 1.972994},
  {"stack_id": "aluminium|mgo|alox|nbtin", "backend": "ibm_marrakesh", "shots": 4096, "wallclock_s": 6.852, "job_id": "d8e3unbo3njc73eu7a10", "hardware": true, "oracle_qubits": 4, "execution_s": 1.966727},
  {"stack_id": "tin-metal|sapphire|aluminium|nbn", "backend": "ibm_marrakesh", "shots": 4096, "wallclock_s": 6.162, "job_id": "d8e3uqbo3njc73eu7a6g", "hardware": true, "oracle_qubits": 4, "execution_s": 1.942666}
    ] as HardwareSample[],
  },
  sweep: [
  { n: 100, classical: 27.975917, gpu: 0.01366, xpyq: 2.238073, ibm: 18.891107 },
  { n: 1000, classical: 279.759167, gpu: 0.136601, xpyq: 6.993979, ibm: 59.03471 },
  { n: 10000, classical: 2797.591667, gpu: 1.366012, xpyq: 22.100974, ibm: 186.549684 },
  { n: 100000, classical: 27975.916667, gpu: 13.660116, xpyq: 69.660033, ibm: 587.985712 },
  { n: 1000000, classical: 279759.166667, gpu: 136.601156, xpyq: 219.890705, ibm: 1856.051282 },
  { n: 10000000, classical: 2797591.666667, gpu: 1366.011556, xpyq: 694.92177, ibm: 5865.688786 },
  { n: 100000000, classical: 27975916.666667, gpu: 13660.11556, xpyq: 2197.228495, ibm: 18546.344494 },
  { n: 1000000000, classical: 279759166.666667, gpu: 136601.155599, xpyq: 6948.378423, ibm: 58649.803691 }
  ],
  barComparison: [{"label": "Classical CPU (O(N) enum)", "timeS": 33.5711, "source": "measured"}, {"label": "IBM Quantum (Grover-scaled)", "timeS": 21.252496, "source": "ibm_hardware"}, {"label": "XpyQ (Grover-scaled)", "timeS": 2.517833, "source": "xpyq_api"}],
  meta: {"generatedAt": "2026-05-31T14:04:58Z", "scaleReference": 1000000},
};

export const MATERIALS_SEARCH_META = MATERIALS_SEARCH_BENCHMARK.meta;
