"""Export the vibha cryostat catalogue to a frontend data file.

Reads cryostat_catalog.py (Tier-1 commercial dilution refrigerators) and emits
src/lib/qa/cryostat-data.ts so the Co-Design Selector's Step 3 (Cryostat) is
driven by the real catalogue. Re-run after editing cryostat_catalog.py:

    conda activate qai
    python -m qec_pipeline.export_catalogs
"""

from __future__ import annotations

import os
import time

from cryostat_catalog import list_for_input_picker

ROOT = os.path.dirname(os.path.dirname(__file__))
OUT_TS = os.path.join(ROOT, "src", "lib", "qa", "cryostat-data.ts")


def num(v) -> str:
    if v is None:
        return "null"
    return repr(round(v, 6) if isinstance(v, float) else v)


def main():
    cryostats = list_for_input_picker()
    rows = []
    for c in cryostats:
        fields = {
            "id": repr(c.cryostat_type.value),
            "name": repr(c.display_name),
            "manufacturer": repr(c.manufacturer),
            "baseTempMK": num(c.base_temperature_mK),
            "operatingTempMK": num(c.typical_operating_temp_mK),
            "coolingPowerUw20mK": num(c.cooling_power_uW_at_20mK),
            "maxCoaxLines": num(c.max_coax_lines),
            "maxQubits": num(c.estimated_max_qubits_multiplexed),
            "cosmicRayShielding": repr(c.cosmic_ray_shielding),
            "vibrationIsolation": repr(c.vibration_isolation),
            "magneticShielding": repr(c.magnetic_shielding),
            "maturityTier": num(c.maturity_tier),
            "notes": repr(c.notes),
        }
        rows.append("  { " + ", ".join(f"{k}: {v}" for k, v in fields.items()) + " }")
    body = ",\n".join(rows)

    ts = f"""// AUTO-GENERATED by qec_pipeline/export_catalogs.py from cryostat_catalog.py.
// Do not edit by hand. Tier-1 commercial dilution refrigerators.

export interface Cryostat {{
  id: string; name: string; manufacturer: string;
  baseTempMK: number; operatingTempMK: number; coolingPowerUw20mK: number;
  maxCoaxLines: number; maxQubits: number;
  cosmicRayShielding: string; vibrationIsolation: string; magneticShielding: string;
  maturityTier: number; notes: string;
}}

export const CRYOSTATS: Cryostat[] = [
{body}
];

export const CRYOSTATS_META = {{
  source: "cryostat_catalog.py",
  total: {len(cryostats)},
  generatedAt: "{time.strftime('%Y-%m-%dT%H:%M:%SZ', time.gmtime())}",
}};
"""
    os.makedirs(os.path.dirname(OUT_TS), exist_ok=True)
    with open(OUT_TS, "w") as f:
        f.write(ts)
    print(f"  wrote {OUT_TS} ({len(cryostats)} cryostats)")
    for c in cryostats:
        print(f"    {c.display_name:<32} base {c.base_temperature_mK} mK · {c.estimated_max_qubits_multiplexed} qubits")


if __name__ == "__main__":
    main()
