/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppTopologyRouteImport } from './routes/_app.topology'
import { Route as AppSurfaceCodeRouteImport } from './routes/_app.surface-code'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppQecRouteImport } from './routes/_app.qec'
import { Route as AppMaterialsRouteImport } from './routes/_app.materials'
import { Route as AppCodesignRouteImport } from './routes/_app.codesign'
import { Route as AppCodeDesignerRouteImport } from './routes/_app.code-designer'
import { Route as AppBenchmarksRouteImport } from './routes/_app.benchmarks'
import { Route as AppAgentRouteImport } from './routes/_app.agent'
import { Route as AppAdvantageRouteImport } from './routes/_app.advantage'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppTopologyRoute = AppTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AppRoute,
} as any)
const AppSurfaceCodeRoute = AppSurfaceCodeRouteImport.update({
  id: '/surface-code',
  path: '/surface-code',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppQecRoute = AppQecRouteImport.update({
  id: '/qec',
  path: '/qec',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppCodesignRoute = AppCodesignRouteImport.update({
  id: '/codesign',
  path: '/codesign',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeDesignerRoute = AppCodeDesignerRouteImport.update({
  id: '/code-designer',
  path: '/code-designer',
  getParentRoute: () => AppRoute,
} as any)
const AppBenchmarksRoute = AppBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)
const AppAdvantageRoute = AppAdvantageRouteImport.update({
  id: '/advantage',
  path: '/advantage',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/advantage': typeof AppAdvantageRoute
  '/agent': typeof AppAgentRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/code-designer': typeof AppCodeDesignerRoute
  '/codesign': typeof AppCodesignRoute
  '/materials': typeof AppMaterialsRoute
  '/qec': typeof AppQecRoute
  '/results': typeof AppResultsRoute
  '/surface-code': typeof AppSurfaceCodeRoute
  '/topology': typeof AppTopologyRoute
  '/workspace': typeof AppWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/advantage': typeof AppAdvantageRoute
  '/agent': typeof AppAgentRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/code-designer': typeof AppCodeDesignerRoute
  '/codesign': typeof AppCodesignRoute
  '/materials': typeof AppMaterialsRoute
  '/qec': typeof AppQecRoute
  '/results': typeof AppResultsRoute
  '/surface-code': typeof AppSurfaceCodeRoute
  '/topology': typeof AppTopologyRoute
  '/workspace': typeof AppWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/advantage': typeof AppAdvantageRoute
  '/_app/agent': typeof AppAgentRoute
  '/_app/benchmarks': typeof AppBenchmarksRoute
  '/_app/code-designer': typeof AppCodeDesignerRoute
  '/_app/codesign': typeof AppCodesignRoute
  '/_app/materials': typeof AppMaterialsRoute
  '/_app/qec': typeof AppQecRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/surface-code': typeof AppSurfaceCodeRoute
  '/_app/topology': typeof AppTopologyRoute
  '/_app/workspace': typeof AppWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/advantage'
    | '/agent'
    | '/benchmarks'
    | '/code-designer'
    | '/codesign'
    | '/materials'
    | '/qec'
    | '/results'
    | '/surface-code'
    | '/topology'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/advantage'
    | '/agent'
    | '/benchmarks'
    | '/code-designer'
    | '/codesign'
    | '/materials'
    | '/qec'
    | '/results'
    | '/surface-code'
    | '/topology'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/advantage'
    | '/_app/agent'
    | '/_app/benchmarks'
    | '/_app/code-designer'
    | '/_app/codesign'
    | '/_app/materials'
    | '/_app/qec'
    | '/_app/results'
    | '/_app/surface-code'
    | '/_app/topology'
    | '/_app/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topology': {
      id: '/_app/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AppTopologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/surface-code': {
      id: '/_app/surface-code'
      path: '/surface-code'
      fullPath: '/surface-code'
      preLoaderRoute: typeof AppSurfaceCodeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qec': {
      id: '/_app/qec'
      path: '/qec'
      fullPath: '/qec'
      preLoaderRoute: typeof AppQecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials': {
      id: '/_app/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/codesign': {
      id: '/_app/codesign'
      path: '/codesign'
      fullPath: '/codesign'
      preLoaderRoute: typeof AppCodesignRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code-designer': {
      id: '/_app/code-designer'
      path: '/code-designer'
      fullPath: '/code-designer'
      preLoaderRoute: typeof AppCodeDesignerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/benchmarks': {
      id: '/_app/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof AppBenchmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/advantage': {
      id: '/_app/advantage'
      path: '/advantage'
      fullPath: '/advantage'
      preLoaderRoute: typeof AppAdvantageRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAdvantageRoute: typeof AppAdvantageRoute
  AppAgentRoute: typeof AppAgentRoute
  AppBenchmarksRoute: typeof AppBenchmarksRoute
  AppCodeDesignerRoute: typeof AppCodeDesignerRoute
  AppCodesignRoute: typeof AppCodesignRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppQecRoute: typeof AppQecRoute
  AppResultsRoute: typeof AppResultsRoute
  AppSurfaceCodeRoute: typeof AppSurfaceCodeRoute
  AppTopologyRoute: typeof AppTopologyRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdvantageRoute: AppAdvantageRoute,
  AppAgentRoute: AppAgentRoute,
  AppBenchmarksRoute: AppBenchmarksRoute,
  AppCodeDesignerRoute: AppCodeDesignerRoute,
  AppCodesignRoute: AppCodesignRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppQecRoute: AppQecRoute,
  AppResultsRoute: AppResultsRoute,
  AppSurfaceCodeRoute: AppSurfaceCodeRoute,
  AppTopologyRoute: AppTopologyRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
