/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppWorkspaceRouteImport } from './routes/_app.workspace'
import { Route as AppTopologyRouteImport } from './routes/_app.topology'
import { Route as AppResultsRouteImport } from './routes/_app.results'
import { Route as AppQecRouteImport } from './routes/_app.qec'
import { Route as AppMaterialsRouteImport } from './routes/_app.materials'
import { Route as AppBenchmarksRouteImport } from './routes/_app.benchmarks'
import { Route as AppAgentRouteImport } from './routes/_app.agent'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWorkspaceRoute = AppWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AppRoute,
} as any)
const AppTopologyRoute = AppTopologyRouteImport.update({
  id: '/topology',
  path: '/topology',
  getParentRoute: () => AppRoute,
} as any)
const AppResultsRoute = AppResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AppRoute,
} as any)
const AppQecRoute = AppQecRouteImport.update({
  id: '/qec',
  path: '/qec',
  getParentRoute: () => AppRoute,
} as any)
const AppMaterialsRoute = AppMaterialsRouteImport.update({
  id: '/materials',
  path: '/materials',
  getParentRoute: () => AppRoute,
} as any)
const AppBenchmarksRoute = AppBenchmarksRouteImport.update({
  id: '/benchmarks',
  path: '/benchmarks',
  getParentRoute: () => AppRoute,
} as any)
const AppAgentRoute = AppAgentRouteImport.update({
  id: '/agent',
  path: '/agent',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent': typeof AppAgentRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/materials': typeof AppMaterialsRoute
  '/qec': typeof AppQecRoute
  '/results': typeof AppResultsRoute
  '/topology': typeof AppTopologyRoute
  '/workspace': typeof AppWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent': typeof AppAgentRoute
  '/benchmarks': typeof AppBenchmarksRoute
  '/materials': typeof AppMaterialsRoute
  '/qec': typeof AppQecRoute
  '/results': typeof AppResultsRoute
  '/topology': typeof AppTopologyRoute
  '/workspace': typeof AppWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/agent': typeof AppAgentRoute
  '/_app/benchmarks': typeof AppBenchmarksRoute
  '/_app/materials': typeof AppMaterialsRoute
  '/_app/qec': typeof AppQecRoute
  '/_app/results': typeof AppResultsRoute
  '/_app/topology': typeof AppTopologyRoute
  '/_app/workspace': typeof AppWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent'
    | '/benchmarks'
    | '/materials'
    | '/qec'
    | '/results'
    | '/topology'
    | '/workspace'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent'
    | '/benchmarks'
    | '/materials'
    | '/qec'
    | '/results'
    | '/topology'
    | '/workspace'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/agent'
    | '/_app/benchmarks'
    | '/_app/materials'
    | '/_app/qec'
    | '/_app/results'
    | '/_app/topology'
    | '/_app/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/workspace': {
      id: '/_app/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AppWorkspaceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/topology': {
      id: '/_app/topology'
      path: '/topology'
      fullPath: '/topology'
      preLoaderRoute: typeof AppTopologyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/results': {
      id: '/_app/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AppResultsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/qec': {
      id: '/_app/qec'
      path: '/qec'
      fullPath: '/qec'
      preLoaderRoute: typeof AppQecRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/materials': {
      id: '/_app/materials'
      path: '/materials'
      fullPath: '/materials'
      preLoaderRoute: typeof AppMaterialsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/benchmarks': {
      id: '/_app/benchmarks'
      path: '/benchmarks'
      fullPath: '/benchmarks'
      preLoaderRoute: typeof AppBenchmarksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agent': {
      id: '/_app/agent'
      path: '/agent'
      fullPath: '/agent'
      preLoaderRoute: typeof AppAgentRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAgentRoute: typeof AppAgentRoute
  AppBenchmarksRoute: typeof AppBenchmarksRoute
  AppMaterialsRoute: typeof AppMaterialsRoute
  AppQecRoute: typeof AppQecRoute
  AppResultsRoute: typeof AppResultsRoute
  AppTopologyRoute: typeof AppTopologyRoute
  AppWorkspaceRoute: typeof AppWorkspaceRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgentRoute: AppAgentRoute,
  AppBenchmarksRoute: AppBenchmarksRoute,
  AppMaterialsRoute: AppMaterialsRoute,
  AppQecRoute: AppQecRoute,
  AppResultsRoute: AppResultsRoute,
  AppTopologyRoute: AppTopologyRoute,
  AppWorkspaceRoute: AppWorkspaceRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
